// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcw-f5sD_SE5xCrBxDORTtlbOy7nmC3M4',
    appId: '1:878143887079:web:551bf9ae9db0f6189d3442',
    messagingSenderId: '878143887079',
    projectId: 'scan2health-2055c',
    authDomain: 'scan2health-2055c.firebaseapp.com',
    storageBucket: 'scan2health-2055c.firebasestorage.app',
    measurementId: 'G-PCZZEK17EE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBNGPSFAEVlpKZiUyFEeXcql8w7h5zQYU',
    appId: '1:878143887079:android:cf8efacf23eb352b9d3442',
    messagingSenderId: '878143887079',
    projectId: 'scan2health-2055c',
    storageBucket: 'scan2health-2055c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC7AKMPDEok1SwF6x-MVS_yYMPKezdQYg',
    appId: '1:878143887079:ios:d821c4e62752fe899d3442',
    messagingSenderId: '878143887079',
    projectId: 'scan2health-2055c',
    storageBucket: 'scan2health-2055c.firebasestorage.app',
    iosBundleId: 'com.example.scan2health',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC7AKMPDEok1SwF6x-MVS_yYMPKezdQYg',
    appId: '1:878143887079:ios:d821c4e62752fe899d3442',
    messagingSenderId: '878143887079',
    projectId: 'scan2health-2055c',
    storageBucket: 'scan2health-2055c.firebasestorage.app',
    iosBundleId: 'com.example.scan2health',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcw-f5sD_SE5xCrBxDORTtlbOy7nmC3M4',
    appId: '1:878143887079:web:e759282f05c1cc339d3442',
    messagingSenderId: '878143887079',
    projectId: 'scan2health-2055c',
    authDomain: 'scan2health-2055c.firebaseapp.com',
    storageBucket: 'scan2health-2055c.firebasestorage.app',
    measurementId: 'G-MH8019KL7T',
  );
}
