import 'package:flutter/material.dart';
import '../core/app_theme.dart';
class PrimaryButton extends StatelessWidget { const PrimaryButton({super.key, required this.label, required this.onPressed, this.icon}); final String label; final VoidCallback? onPressed; final IconData? icon;
  @override Widget build(BuildContext context) => SizedBox(width: double.infinity, height: 54, child: FilledButton.icon(onPressed: onPressed, icon: icon == null ? const SizedBox.shrink() : Icon(icon), label: Text(label), style: FilledButton.styleFrom(backgroundColor: AppTheme.primaryGreen, shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)))));
}
class SocialButton extends StatelessWidget { const SocialButton({super.key, required this.label, required this.icon}); final String label; final IconData icon;
  @override Widget build(BuildContext context) => SizedBox(width: double.infinity, height: 52, child: OutlinedButton.icon(onPressed: () {}, icon: Icon(icon, color: AppTheme.ink), label: Text(label), style: OutlinedButton.styleFrom(foregroundColor: AppTheme.ink, shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)), side: const BorderSide(color: Color(0xFFDCE6E0)))));
}
class AppTextField extends StatefulWidget { const AppTextField({super.key, required this.hint, required this.icon, this.password = false, this.keyboardType, this.controller, this.enabled = true, this.autofillHints, this.textInputAction, this.onFieldSubmitted}); final String hint; final IconData icon; final bool password; final TextInputType? keyboardType; final TextEditingController? controller; final bool enabled; final Iterable<String>? autofillHints; final TextInputAction? textInputAction; final ValueChanged<String>? onFieldSubmitted; @override State<AppTextField> createState() => _AppTextFieldState(); }
class _AppTextFieldState extends State<AppTextField> { bool hidden = true; @override Widget build(BuildContext context) => TextFormField(controller: widget.controller, enabled: widget.enabled, keyboardType: widget.keyboardType, autofillHints: widget.autofillHints, textInputAction: widget.textInputAction, onFieldSubmitted: widget.onFieldSubmitted, obscureText: widget.password && hidden, decoration: InputDecoration(hintText: widget.hint, prefixIcon: Icon(widget.icon, color: AppTheme.muted), suffixIcon: widget.password ? IconButton(onPressed: widget.enabled ? () => setState(() => hidden = !hidden) : null, icon: Icon(hidden ? Icons.visibility_off_outlined : Icons.visibility_outlined)) : null)); }
